version: "3.7"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DYNO: 'true'
    volumes:
      - "./app:/app"
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      DYNO: 'true'
      REDIS_URL: 'redis'
    volumes:
      - "./app:/app"
    depends_on:
      - redis
    links:
      - redis
    restart: always
  redis:
    image: redis
